// app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "VectorEdge",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              // This script now uses a function to avoid immediate execution issues.
              (function() {
                try {
                  const theme = localStorage.getItem('theme');
                  if (theme) {
                    document.documentElement.classList.add(theme);
                  } else if (window.matchMedia('(prefers-color-scheme: dark)').matches) {
                    document.documentElement.classList.add('dark');
                  }
                } catch (e) {
                  console.error('Error setting theme from script:', e);
                }
              })();
            `,
          }}
        />
      </head>
      {/* THE FIX: Add suppressHydrationWarning here as well */}
      <body className="" suppressHydrationWarning>
        {children}
      </body>
    </html>
  );
}